language: elixir

sudo: false

elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.3
  - 1.6.0

otp_release:
  - 18.3
  - 19.3
  - 20.2

script:
  - MIX_ENV=docs mix do deps.get, inch.report
  - MIX_ENV=test mix do deps.get, compile, coveralls.travis

matrix:
  exclude:
  - elixir: 1.3.4
    otp_release: 20.0
  - elixir: 1.6.0
    otp_release: 18.3
